// components/studio/create/atelierStyle.js
//
// LESHEM.S OS — Clean 8L: "Atelier White" visual system.
//
// Local, ISOLATED style values for the flagship /studio/create experience
// only. components/studio/shared/tokens.js (shared by ~60 other components)
// is NOT modified — this file layers a warm-ivory / calm / image-first
// direction on top of it, scoped entirely to AtelierCreateShell.js and its
// child views. No CSS module, no new package — same inline-style approach
// already used throughout components/studio/create.

import { tokens } from '../shared/tokens';

export const atelier = {
  color: {
    // Warm near-white app background (tokens.ivory is a cooler neutral gray;
    // this is the milestone's specific "warm ivory" surface, used ONLY here).
    warmBg: '#FAF8F4',
    surface: tokens.color.canvas,
    border: '#EDE7DD',
    ink: tokens.color.charcoal,
    inkSoft: tokens.color.inkSoft,
    inkFaint: tokens.color.inkFaint,
    gold: tokens.color.gold,
    goldFaint: '#F4EEE0',
    sage: tokens.color.sage,
    sageFaint: tokens.color.sageFaint,
  },
  radius: {
    sm: '6px',
    md: '10px',
    lg: '16px',
    pill: '999px',
  },
  shadow: {
    soft: '0 1px 2px rgba(20,18,14,0.04), 0 6px 18px rgba(20,18,14,0.05)',
  },
  font: {
    display: tokens.font.display,
    body: tokens.font.body,
  },
};

export const styles = {
  page: {
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
    minHeight: '100%',
    background: atelier.color.warmBg,
    padding: '4px',
    boxSizing: 'border-box',
  },
  contextBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '10px',
    padding: '10px 14px',
    borderRadius: atelier.radius.md,
    background: atelier.color.surface,
    border: `1px solid ${atelier.color.border}`,
  },
  contextBarLeft: { display: 'flex', alignItems: 'center', gap: '10px', minWidth: 0 },
  backBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '36px',
    height: '36px',
    borderRadius: atelier.radius.sm,
    border: `1px solid ${atelier.color.border}`,
    background: 'transparent',
    color: atelier.color.ink,
    cursor: 'pointer',
    flexShrink: 0,
  },
  contextTitle: {
    fontFamily: atelier.font.body,
    fontWeight: 700,
    fontSize: '13.5px',
    color: atelier.color.ink,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  contextStage: {
    fontFamily: atelier.font.body,
    fontSize: '11.5px',
    fontWeight: 600,
    color: atelier.color.gold,
  },
  menuBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '36px',
    height: '36px',
    borderRadius: atelier.radius.sm,
    border: `1px solid ${atelier.color.border}`,
    background: 'transparent',
    color: atelier.color.inkSoft,
    cursor: 'pointer',
    flexShrink: 0,
    position: 'relative',
  },
  menuSheet: {
    position: 'absolute',
    insetInlineEnd: 0,
    top: '42px',
    zIndex: 20,
    display: 'flex',
    flexDirection: 'column',
    minWidth: '180px',
    background: atelier.color.surface,
    border: `1px solid ${atelier.color.border}`,
    borderRadius: atelier.radius.md,
    boxShadow: atelier.shadow.soft,
    overflow: 'hidden',
  },
  menuItem: {
    padding: '11px 14px',
    fontFamily: atelier.font.body,
    fontSize: '13px',
    fontWeight: 600,
    color: atelier.color.ink,
    background: 'transparent',
    border: 'none',
    textAlign: 'right',
    cursor: 'pointer',
  },
  stateCard: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    padding: '20px',
    borderRadius: atelier.radius.lg,
    background: atelier.color.surface,
    border: `1px solid ${atelier.color.border}`,
    boxShadow: atelier.shadow.soft,
  },
  headline: {
    fontFamily: atelier.font.display,
    fontSize: '22px',
    fontWeight: 700,
    color: atelier.color.ink,
    margin: 0,
    textAlign: 'center',
  },
  question: {
    fontFamily: atelier.font.body,
    fontSize: '14.5px',
    color: atelier.color.inkSoft,
    margin: 0,
    textAlign: 'center',
  },
  primaryPathBtn: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    padding: '20px',
    borderRadius: atelier.radius.md,
    border: `1px solid ${atelier.color.gold}`,
    background: atelier.color.goldFaint,
    cursor: 'pointer',
    textAlign: 'center',
  },
  primaryPathTitle: {
    fontFamily: atelier.font.display,
    fontSize: '16.5px',
    fontWeight: 700,
    color: atelier.color.ink,
  },
  primaryPathSub: {
    fontFamily: atelier.font.body,
    fontSize: '12.5px',
    color: atelier.color.inkSoft,
  },
  quietRow: { display: 'flex', gap: '8px', flexWrap: 'wrap', justifyContent: 'center' },
  quietChip: {
    padding: '8px 14px',
    borderRadius: atelier.radius.pill,
    border: `1px solid ${atelier.color.border}`,
    background: 'transparent',
    color: atelier.color.inkFaint,
    fontFamily: atelier.font.body,
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'default',
  },
  intakeWrap: { display: 'flex', flexDirection: 'column', gap: '6px' },
  intakeLabel: {
    fontFamily: atelier.font.body,
    fontSize: '12.5px',
    fontWeight: 700,
    color: atelier.color.inkSoft,
    textAlign: 'center',
  },
  textarea: {
    width: '100%',
    boxSizing: 'border-box',
    fontFamily: atelier.font.body,
    fontSize: '14px',
    color: atelier.color.ink,
    background: atelier.color.warmBg,
    border: `1px solid ${atelier.color.border}`,
    borderRadius: atelier.radius.md,
    padding: '14px 16px',
    resize: 'vertical',
    lineHeight: 1.6,
  },
  stoneFocus: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '10px',
    padding: '18px',
  },
  stoneImageWrap: {
    width: '160px',
    height: '160px',
    borderRadius: atelier.radius.lg,
    overflow: 'hidden',
    border: `1px solid ${atelier.color.border}`,
  },
  stoneImage: { width: '100%', height: '100%', objectFit: 'cover' },
  stoneName: {
    fontFamily: atelier.font.display,
    fontSize: '16px',
    fontWeight: 700,
    color: atelier.color.ink,
  },
  emptyStoneBox: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '10px',
    padding: '28px 16px',
    borderRadius: atelier.radius.md,
    border: `1px dashed ${atelier.color.border}`,
    color: atelier.color.inkFaint,
    fontFamily: atelier.font.body,
    fontSize: '13px',
    textAlign: 'center',
  },
  understandingCard: {
    padding: '18px',
    borderRadius: atelier.radius.md,
    background: atelier.color.goldFaint,
    border: `1px solid ${atelier.color.gold}`,
  },
  understandingEyebrow: {
    fontFamily: atelier.font.body,
    fontSize: '11.5px',
    fontWeight: 800,
    color: atelier.color.gold,
    marginBottom: '6px',
    display: 'block',
  },
  understandingText: {
    fontFamily: atelier.font.body,
    fontSize: '15px',
    fontWeight: 600,
    color: atelier.color.ink,
    lineHeight: 1.6,
    margin: 0,
  },
  directionList: { display: 'flex', flexDirection: 'column', gap: '12px' },
  directionCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    textAlign: 'right',
    padding: '16px',
    borderRadius: atelier.radius.md,
    border: `1px solid ${atelier.color.border}`,
    background: atelier.color.warmBg,
    cursor: 'pointer',
  },
  directionCardOn: {
    border: `1px solid ${atelier.color.gold}`,
    background: atelier.color.surface,
    boxShadow: `0 0 0 1px ${atelier.color.gold}`,
  },
  directionVisual: {
    height: '120px',
    borderRadius: atelier.radius.sm,
    overflow: 'hidden',
  },
  directionName: {
    fontFamily: atelier.font.display,
    fontSize: '15px',
    fontWeight: 700,
    color: atelier.color.ink,
  },
  directionDesc: {
    fontFamily: atelier.font.body,
    fontSize: '13px',
    color: atelier.color.ink,
    lineHeight: 1.55,
  },
  directionMeta: {
    fontFamily: atelier.font.body,
    fontSize: '11.5px',
    color: atelier.color.inkSoft,
  },
  presentationRow: {
    display: 'flex',
    gap: '10px',
    alignItems: 'baseline',
    padding: '8px 12px',
    borderRadius: atelier.radius.sm,
    background: atelier.color.warmBg,
    border: `1px solid ${atelier.color.border}`,
  },
  presentationKey: {
    fontFamily: atelier.font.body,
    fontSize: '11.5px',
    fontWeight: 800,
    color: atelier.color.gold,
    minWidth: '90px',
    flex: '0 0 auto',
  },
  presentationVal: {
    fontFamily: atelier.font.body,
    fontSize: '13px',
    fontWeight: 600,
    color: atelier.color.ink,
    minWidth: 0,
    overflowWrap: 'anywhere',
  },
  savedNote: {
    fontFamily: atelier.font.body,
    fontSize: '12.5px',
    color: atelier.color.sage,
    fontStyle: 'italic',
  },
  nav: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '10px' },
  navActions: { display: 'inline-flex', alignItems: 'center', gap: '8px' },
  primaryBtn: {
    minHeight: '46px',
    padding: '10px 24px',
    borderRadius: atelier.radius.pill,
    border: 'none',
    background: atelier.color.ink,
    color: '#FFFFFF',
    fontFamily: atelier.font.body,
    fontSize: '14px',
    fontWeight: 700,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  primaryBtnDisabled: { opacity: 0.4, cursor: 'not-allowed' },
  secondaryBtn: {
    minHeight: '44px',
    padding: '10px 18px',
    borderRadius: atelier.radius.pill,
    border: `1px solid ${atelier.color.ink}`,
    background: 'transparent',
    color: atelier.color.ink,
    fontFamily: atelier.font.body,
    fontSize: '13px',
    fontWeight: 700,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  ghostBtn: {
    minHeight: '40px',
    padding: '9px 16px',
    borderRadius: atelier.radius.pill,
    border: `1px solid ${atelier.color.border}`,
    background: 'transparent',
    color: atelier.color.inkSoft,
    fontFamily: atelier.font.body,
    fontSize: '12.5px',
    fontWeight: 600,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  successCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    padding: '18px',
    borderRadius: atelier.radius.md,
    border: `1px solid ${atelier.color.sage}`,
    background: atelier.color.sageFaint,
  },
  successTitle: {
    fontFamily: atelier.font.display,
    fontSize: '18px',
    fontWeight: 700,
    color: atelier.color.ink,
  },
  successActions: { display: 'flex', gap: '8px', flexWrap: 'wrap' },
  loading: {
    padding: '24px',
    fontFamily: atelier.font.body,
    fontSize: '13px',
    color: atelier.color.inkFaint,
    textAlign: 'center',
  },
};
