import { atelier, styles as atelierStyles } from './atelierStyle';

export const flagship = atelier;
export const baseStyles = atelierStyles;

export const styles = {
  ...atelierStyles,

  page: {
    ...atelierStyles.page,
    minHeight: '100vh',
    padding: '26px clamp(18px, 3vw, 44px) 42px',
    gap: '16px',
  },
  shell: {
    width: 'min(1260px, 100%)',
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  stateCard: {
    ...atelierStyles.stateCard,
    padding: 'clamp(22px, 3vw, 38px)',
    minHeight: 'min(720px, calc(100vh - 150px))',
    justifyContent: 'center',
    boxShadow: '0 14px 38px rgba(38,35,31,.07)',
  },
  contextBar: {
    ...atelierStyles.contextBar,
    minHeight: '58px',
    padding: '9px 14px',
    boxShadow: '0 4px 18px rgba(38,35,31,.04)',
  },

  progressWrap: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0',
    overflowX: 'auto',
    padding: '2px 4px 6px',
  },
  progressItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '7px',
    minWidth: '92px',
    color: flagship.color.inkFaint,
    fontFamily: flagship.font.body,
    fontSize: '10.5px',
    fontWeight: 700,
    whiteSpace: 'nowrap',
  },
  progressDot: {
    width: '23px',
    height: '23px',
    borderRadius: '50%',
    border: `1px solid ${flagship.color.border}`,
    background: flagship.color.surface,
    display: 'grid',
    placeItems: 'center',
    fontSize: '10px',
    flex: '0 0 auto',
  },
  progressDotDone: {
    background: flagship.color.gold,
    borderColor: flagship.color.gold,
    color: '#fff',
  },
  progressDotActive: {
    borderColor: flagship.color.gold,
    color: flagship.color.gold,
    boxShadow: `0 0 0 3px ${flagship.color.goldFaint}`,
  },
  progressLine: {
    width: '34px',
    height: '1px',
    background: flagship.color.border,
    flex: '0 0 auto',
    marginInline: '3px',
  },
  progressLineDone: { background: flagship.color.gold },

  welcomeHero: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '10px',
  },
  headline: {
    ...atelierStyles.headline,
    fontSize: 'clamp(27px, 3vw, 42px)',
    letterSpacing: '-0.025em',
  },
  question: {
    ...atelierStyles.question,
    fontSize: 'clamp(14px, 1.5vw, 17px)',
  },
  entryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: '16px',
    margin: '14px 0 8px',
  },
  entryCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '11px',
    padding: '12px 12px 18px',
    minHeight: '252px',
    borderRadius: flagship.radius.lg,
    border: `1px solid ${flagship.color.border}`,
    background: flagship.color.surface,
    cursor: 'pointer',
    textAlign: 'center',
    overflow: 'hidden',
    transition: 'transform .18s ease, box-shadow .18s ease, border-color .18s ease',
  },
  entryArt: {
    height: '145px',
    borderRadius: '13px',
    overflow: 'hidden',
  },
  entryTitle: {
    fontFamily: flagship.font.display,
    fontSize: '19px',
    fontWeight: 700,
    color: flagship.color.ink,
  },
  entrySub: {
    fontFamily: flagship.font.body,
    fontSize: '13px',
    lineHeight: 1.45,
    color: flagship.color.inkSoft,
  },
  entryArrow: {
    alignSelf: 'center',
    width: '34px',
    height: '34px',
    borderRadius: '50%',
    display: 'grid',
    placeItems: 'center',
    background: flagship.color.gold,
    color: '#fff',
    fontSize: '18px',
  },
  smartIntake: {
    width: 'min(740px, 100%)',
    margin: '18px auto 0',
    padding: '8px 9px 8px 14px',
    display: 'flex',
    alignItems: 'flex-end',
    gap: '9px',
    border: `1px solid ${flagship.color.border}`,
    borderRadius: '18px',
    background: flagship.color.warmBg,
  },
  smartTextarea: {
    ...atelierStyles.textarea,
    minHeight: '48px',
    padding: '11px 12px',
    background: 'transparent',
    border: 'none',
    resize: 'none',
  },
  sendBtn: {
    width: '44px',
    height: '44px',
    borderRadius: '50%',
    border: 'none',
    display: 'grid',
    placeItems: 'center',
    flex: '0 0 auto',
    background: flagship.color.ink,
    color: '#fff',
    fontSize: '18px',
    cursor: 'pointer',
  },

  splitLayout: {
    display: 'grid',
    gridTemplateColumns: 'minmax(300px, .95fr) minmax(360px, 1.05fr)',
    gap: '32px',
    alignItems: 'stretch',
    minHeight: '510px',
  },
  visualPanel: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '12px',
    padding: '20px',
    borderRadius: flagship.radius.lg,
    background: '#F5F1EA',
    border: `1px solid ${flagship.color.border}`,
    minHeight: '460px',
  },
  stoneImageWrap: {
    width: 'min(420px, 88%)',
    aspectRatio: '1 / 1',
    borderRadius: '22px',
    overflow: 'hidden',
    border: `1px solid ${flagship.color.border}`,
    background: '#fff',
    boxShadow: '0 18px 44px rgba(38,35,31,.09)',
  },
  stoneImage: { width: '100%', height: '100%', objectFit: 'contain' },
  stoneName: {
    ...atelierStyles.stoneName,
    fontSize: '18px',
  },
  formPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
    justifyContent: 'center',
  },
  stageTitle: {
    margin: 0,
    fontFamily: flagship.font.display,
    fontSize: 'clamp(24px, 2.4vw, 34px)',
    color: flagship.color.ink,
    fontWeight: 700,
  },
  stageLead: {
    margin: 0,
    fontFamily: flagship.font.body,
    fontSize: '14px',
    color: flagship.color.inkSoft,
    lineHeight: 1.55,
  },
  requestTextarea: {
    ...atelierStyles.textarea,
    minHeight: '140px',
    background: flagship.color.surface,
    fontSize: '16px',
    padding: '18px',
    resize: 'vertical',
  },

  understandingLayout: {
    display: 'grid',
    gridTemplateColumns: 'minmax(280px, .8fr) minmax(420px, 1.2fr)',
    gap: '28px',
    alignItems: 'center',
  },
  understandingCard: {
    ...atelierStyles.understandingCard,
    padding: '26px',
    borderRadius: flagship.radius.lg,
  },
  understandingText: {
    ...atelierStyles.understandingText,
    fontSize: '18px',
    lineHeight: 1.65,
  },
  summaryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '9px',
  },
  presentationRow: {
    ...atelierStyles.presentationRow,
    flexDirection: 'column',
    gap: '3px',
    alignItems: 'stretch',
    padding: '12px 14px',
  },
  presentationKey: {
    ...atelierStyles.presentationKey,
    minWidth: 0,
  },

  directionList: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: '16px',
  },
  directionCard: {
    ...atelierStyles.directionCard,
    minHeight: '430px',
    padding: '14px',
    background: flagship.color.surface,
    textAlign: 'center',
    gap: '10px',
  },
  directionVisual: {
    height: '230px',
    borderRadius: '13px',
    overflow: 'hidden',
    background: '#F6F3ED',
    display: 'grid',
    placeItems: 'center',
    color: '#777065',
  },
  directionName: {
    ...atelierStyles.directionName,
    fontSize: '18px',
  },
  directionDesc: {
    ...atelierStyles.directionDesc,
    textAlign: 'center',
    minHeight: '42px',
  },
  directionMeta: {
    ...atelierStyles.directionMeta,
    textAlign: 'center',
  },

  refineLayout: {
    display: 'grid',
    gridTemplateColumns: 'minmax(340px, 1fr) minmax(360px, 1fr)',
    gap: '28px',
    alignItems: 'center',
  },
  quickChipRow: { display: 'flex', gap: '8px', flexWrap: 'wrap' },
  quickChip: {
    padding: '8px 13px',
    borderRadius: flagship.radius.pill,
    border: `1px solid ${flagship.color.border}`,
    background: 'transparent',
    color: flagship.color.inkSoft,
    fontFamily: flagship.font.body,
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
  },

  renderLayout: {
    display: 'grid',
    gridTemplateColumns: 'minmax(360px, .95fr) minmax(480px, 1.05fr)',
    gap: '24px',
    alignItems: 'stretch',
  },
  renderControls: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '12px',
  },
  presetGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    padding: '13px',
    borderRadius: flagship.radius.md,
    border: `1px solid ${flagship.color.border}`,
    background: flagship.color.warmBg,
  },
  presetGroupWide: { gridColumn: '1 / -1' },
  presetGroupLabel: {
    fontFamily: flagship.font.body,
    fontSize: '11.5px',
    fontWeight: 800,
    color: flagship.color.ink,
  },
  presetRow: { display: 'flex', gap: '8px', flexWrap: 'wrap' },
  sceneGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: '8px',
  },
  sceneBtn: {
    padding: '6px',
    borderRadius: '11px',
    border: `1px solid ${flagship.color.border}`,
    background: flagship.color.surface,
    cursor: 'pointer',
    fontFamily: flagship.font.body,
    fontSize: '10.5px',
    color: flagship.color.ink,
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
  },
  sceneBtnOn: {
    borderColor: flagship.color.gold,
    boxShadow: `0 0 0 1px ${flagship.color.gold}`,
  },
  presetChip: {
    padding: '9px 14px',
    borderRadius: flagship.radius.pill,
    border: `1px solid ${flagship.color.border}`,
    background: flagship.color.surface,
    color: flagship.color.ink,
    fontFamily: flagship.font.body,
    fontSize: '12.5px',
    fontWeight: 600,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  presetChipOn: {
    borderColor: flagship.color.gold,
    background: flagship.color.goldFaint,
    fontWeight: 700,
  },

  iconActionGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: '10px',
  },
  iconActionBtn: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '6px',
    padding: '14px',
    borderRadius: flagship.radius.md,
    border: `1px solid ${flagship.color.border}`,
    background: flagship.color.surface,
    color: flagship.color.ink,
    fontFamily: flagship.font.body,
    fontSize: '12.5px',
    fontWeight: 700,
    cursor: 'pointer',
    textAlign: 'center',
  },
  copyBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    padding: '12px',
    borderRadius: flagship.radius.md,
    border: `1px solid ${flagship.color.border}`,
    background: flagship.color.warmBg,
  },
  copyBlockText: {
    margin: 0,
    fontFamily: flagship.font.body,
    fontSize: '12px',
    color: flagship.color.inkSoft,
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
    maxHeight: '160px',
    overflow: 'auto',
  },
  clientCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    padding: '22px',
    borderRadius: flagship.radius.lg,
    background: flagship.color.surface,
    border: `1px solid ${flagship.color.gold}`,
    textAlign: 'center',
  },
  clientDesc: {
    fontFamily: flagship.font.display,
    fontSize: '15px',
    color: flagship.color.ink,
    lineHeight: 1.7,
  },

  nav: {
    ...atelierStyles.nav,
    marginTop: 'auto',
    paddingTop: '6px',
  },
};
